l,m,n,o,p,q = input().split()
l = int(l)
m = int(m)
n = int(n)
o = int(o)
p = int(p)
q = int(q)
a = int(1)
b = int(2)
c = int(8)
print ((a-l),end = ' ')
print ((a-m),end = ' ')
print ((b-n),end = ' ')
print ((b-o),end = ' ')
print ((b-p),end = ' ')
print ((c-q))
